# Generated by Django 4.1.5 on 2023-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="no_of_guests",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="Inventory",
            field=models.SmallIntegerField(),
        ),
    ]
