# Generated by Django 4.1.5 on 2023-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guests_alter_menu_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("guest_number", models.IntegerField()),
                ("comment", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="MenuTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("description", models.TextField(default="", max_length=1000)),
            ],
        ),
    ]
